config/routes.rb
Workspace::Application.routes.draw do
  devise_for :admins
  resources :roles

  devise_for :users
  get "welcome/index"
  resources :chats

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:role_id, :email, :password, :password_confirmation, :remember_me) }
  devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :role_id, :email, :password, :remember_me) }
  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:role_id, :email, :password, :password_confirmation, :current_password) }
end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :role, only: [:edit, :update, :destroy]
  # GET /chats
  # GET /chats.json
  
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chat }
      else
        format.html { render action: 'new' }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end
    
    def role
      if current_user.role_id==1 || current_user.role_id==2
        logger.info("I am admin")
      else
        logger.info("I am not admin")
        redirect_to  welcome_index_path , notice: 'Unauthorized Access.'
        
      end
      
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:message)
    end
end

app/controllers/registrations_controller_controller.rb
class RegistrationsControllerController < DeviseController

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @role }
      else
        format.html { render action: 'new' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:role_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/registrations_controller_helper.rb
module RegistrationsControllerHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/chats/_form.html.erb
<%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<h1>Listing chats</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.message %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p>
  <strong>Message:</strong>
  <%= @chat.message %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>
    <%= link_to 'User Edit Profile', edit_user_registration_path, :class => 'navbar-link'%> | 
    <%= link_to 'User Logout', destroy_user_session_path, method: :delete,:class => 'navbar-link'%>
  <% else %>
    <%= link_to 'User sign up', new_user_registration_path, :class => 'navbar-link' %> | 
    <%= link_to 'User login', new_user_session_path, :class => 'navbar-link' %>
  <% end %><br>
  <% if admin_signed_in? %>
    Logged in as <strong><%= current_admin.email %></strong>
    <%= link_to 'Admin Edit Profile', edit_admin_registration_path, :class => 'navbar-link'%> | 
    <%= link_to 'Admin Logout', destroy_admin_session_path, method: :delete,:class => 'navbar-link'%>
  <% else %>
    <%= link_to 'Admin sign up', new_admin_registration_path, :class => 'navbar-link' %> | 
    <%= link_to 'Admin login', new_admin_session_path, :class => 'navbar-link' %>
  <% end %>
</p>

<% if notice %>
  <p class="alert alert-success">
    <%=notice%>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger">
    <%= alert %>
  </p>
<% end %>
<%= yield %>

</body>
</html>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role_name %><br>
    <%= f.text_field :role_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <thead>
    <tr>
      <th>Role name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.role_name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role name:</strong>
  <%= @role.role_name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>